### ISSUE TITLE
Ref: brigade chart: global image.{repository,tag} values?

### ISSUE THREAD

**Issue by vdice** [brigadecore/charts#1]
Wondering if it'd be worth refactoring charts/brigade to use a top-level/global `image` config, primarily for setting `image.repository` and `image.tag` to be used by all deployments.  (Currently, each component's `image` config needs changing when non-defaults are desired.)

(Migrated from https://github.com/Azure/brigade-charts/issues/3)

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
