### ISSUE TITLE
Charts should not use latest tag

### ISSUE THREAD

**Issue by krancour** [brigadecore/charts#14]
Most of the charts in this repo use images tagged with `latest` or do not specify a tag-- which, to Docker, _implies_ `latest`.

This is not a good practice as it creates the possibility that, depending on the image pull policy, a newer version of an image that was perhaps not desired can be pulled and used. Even worse, the newer image in question could be incompatible with the chart. Worse still, different versions of the image could exist on different nodes in the cluster...

Going forward, could I propose that we only use images with immutable semver tags?

**Comment by technosophos** [comment]
I'd be all for semver tags.

**Comment by technosophos** [comment]
@mattfarina and I even wrote a tool to auto-increment semver for CI pipelines. https://github.com/Masterminds/vert

**Comment by vdice** [comment]
While I'd want to point out that _mostly_ the default tag used in the templates (when not provided in a values.yaml file) is the semver `Chart.AppVersion` (e.g. https://github.com/brigadecore/charts/blob/master/charts/brigade/templates/api-deployment.yaml#L26), I'm sure there are spots where we're either lax or perhaps could use stricter enforcement/clarity.  Ok, perhaps _mostly_ only really means the main `brigade` chart 😅 

LIkewise, however, I'm definitely in support of an audit and making sure semver tags are used for defaults for all images.

**Comment by krancour** [comment]
This has been adequately addressed since the 1.1 release. The only exception is the Kashti image is still addressed using a `latest` tag, but we just cut a Kashti v0.3.0 image. I'll keep this open until the Kashti chart is fixed up as well as the overall Brigade chart, which depends on the Kashti chart, but I just wanted to report that there has been major progress on this issue.

**Comment by krancour** [comment]
This has been fully addressed since #31. Closing.
