### ISSUE TITLE
generic service should allow setting annotations

### ISSUE THREAD

**Issue by scottambroseio** [brigadecore/charts#19]
Hey all :wave:

Currently, the brigade chart doesn't allow setting custom annotations on the generic gateway service (and maybe other services as well). The general use case I see for this is for those of us who are running ambassador on our clusters and want to handle ingress using it.

It would be a nice QoL addition for this to be a configuration option for the chart rather than an extra manual step via kubectl annotate or similar.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
