### ISSUE TITLE
Namespace setting in project values file seems to be ignored

### ISSUE THREAD

**Issue by brandon-bethke-timu** [brigadecore/charts#44]
I tried to use the 'namespace' feature, but it did not seem to work. The feature where builds get deployed into the specified namespace.
I researched why and it seems that namespace field in the project's values.yaml file is ignored. 
Specifically, the helm template which constructs the project secret does not use the namespace value in the project's values.yaml.
The only way that I can determine to use this feature is to create a custom gateway that sets the namespace on the store object. I have not verified this yet though.
Consequently, this line of code in kube/project.go - NewProjectFromSecret 
`proj.Kubernetes.Namespace = def(secret.Data["namespace"], namespace)`
can never use the value from the secret because it's never there.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.

Also please note that v2 has taken all of this into consideration and automatically isolates every _project_ to its own namespace.
