### ISSUE TITLE
Helm Configurable Liveness Probe Setting

### ISSUE THREAD

**Issue by brandon-bethke-timu** [brigadecore/charts#47]
Please make the livenessProbe settings such as:

```
periodSeconds
initialDelaySeconds
timeoutSeconds
```

configurable through helm values.

**Comment by radu-matei** [comment]
Initially filed in the Kashti reepo, but relevant to more charts.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
