### ISSUE TITLE
Spurious message telling me my Brigade repo is wrong

### ISSUE THREAD

**Issue by technosophos** [brigadecore/charts#50]
Helm version: `version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.5"}`

Doing a fresh install of Brigade, I did the following:

```console
$ helm repo add brigade https://brigadecore.github.io/charts
$ helm repo list
NAME   	URL
brigade	https://brigadecore.github.io/charts
stable 	https://kubernetes-charts.storage.googleapis.com/
$ helm install brigade brigade/brigade
NAME: brigade
LAST DEPLOYED: 2019-11-04 16:38:12.298867 -0700 MST m=+1.685438437
NAMESPACE: default
STATUS: deployed
NOTES:
Brigade is now installed!

To find out about your newly configured system, run:

  $ helm status brigade

NOTE: The Helm repo URL serving this chart has changed to: https://brigadecore.github.io/charts

All subsequent chart releases will be served at this URL.

Please update your local Helm repo:

  helm repo remove brigade
  helm repo add brigade https://brigadecore.github.io/charts
```

The `NOTE` at the bottom seems spurious. The URL it recommends is the URL I used.

**Comment by vdice** [comment]
Thanks @technosophos for filing.  We intro'd this disclaimer around the time of the chart repo transition to this `brigadecore` org but it is indeed overdue for removal.  PR to do so in https://github.com/brigadecore/charts/pull/51.
