### ISSUE TITLE
Secret Name Value

### ISSUE THREAD

**Issue by t0ster** [brigadecore/charts#70]
This is a small request, however having option to define a secret name for the chart instead of passing `defaultSharedSecret` and `key` values would be really nice. This is useful in case of following GitOps approach, [Flux](https://github.com/fluxcd/flux) with [Helm Operator](https://github.com/fluxcd/helm-operator) and storing secrets in Git with [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets).

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
