### ISSUE TITLE
brigade-project chart: missing "sshCert" key

### ISSUE THREAD

**Issue by skomma** [brigadecore/charts#71]
The new "sshCert" key is needed in a brigade project Secret to run jobs when using brigade 1.3.0.

https://github.com/brigadecore/brigade/pull/1008

But, brigade-project chart currently doesn't support it.
Do you have any plans to support it?

**Comment by vdice** [comment]
Thanks for the issue!  Sure, I think we could support it.  It should be as simple as adding a section similar to the current `sshKey` section here: https://github.com/brigadecore/charts/blob/master/charts/brigade-project/templates/secret.yaml#L60-L62  

This time, the key would be `sshCert`.  A PR would be welcome!

**Comment by skomma** [comment]
This issue seems to be resolved in #77.
But brigade-project chart in Helm repository has not released yet.

Do you have any plans to release this chart?

**Comment by krancour** [comment]
Sure. We can take a look at releasing what's currently in master for that chart.

**Comment by krancour** [comment]
@skomma sorry for the delay. We did release a v1.1.0 of the project chart yesterday.
