### ISSUE TITLE
Allow configurable ingress path value in Kashti chart

### ISSUE THREAD

**Issue by Topher-the-Geek** [brigadecore/charts#88]
For my installation at least, with AWS Load Balancer, [this line requires a star](https://github.com/brigadecore/charts/blob/c04cb812233726613a233dc561d5581242d68d14/charts/kashti/templates/ingress.yaml#L23)

```
path: /*
```

I see the ingress for the Brigade API server already supports a setting from `values.yaml`. Kashti needs that too.

**Comment by vdice** [comment]
@Topher-the-Geek thank you for the issue.  Indeed, it would be useful to allow users installing the Kashti chart to supply ingress path value(s) that suit their needs.  Here are the links to how it is done for the Brigade API server: https://github.com/brigadecore/charts/blob/master/charts/brigade/templates/api-ingress.yaml#L23-L25 and https://github.com/brigadecore/charts/blob/master/charts/brigade/values.yaml#L137-L138

**Comment by krancour** [comment]
We're drawing closer to v1's EOL, so I'm closing this stale issue. It can be re-opened if truly needed.
